//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Resources.Views.Shared.Components.SensorSettings {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Default {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Default() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Site.Resources.Views.Shared.Components.SensorSettings.Default", typeof(Default).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Please_log_in_before_updating_your_settings___WaterAlarm_be_will_send_you_an_e_mail_with_a_link_to_verify_your_identity___When_you_click_the_link__you_will_get_back_to_this_page_ {
            get {
                return ResourceManager.GetString("Please log in before updating your settings.  WaterAlarm.be will send you an e-ma" +
                        "il with a link to verify your identity.  When you click the link, you will get b" +
                        "ack to this page.", resourceCulture);
            }
        }
        
        internal static string Submit_changes {
            get {
                return ResourceManager.GetString("Submit changes", resourceCulture);
            }
        }
        
        internal static string liter {
            get {
                return ResourceManager.GetString("liter", resourceCulture);
            }
        }
        
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        internal static string Distance_to_water_when_empty__0__ {
            get {
                return ResourceManager.GetString("Distance to water when empty (0%)", resourceCulture);
            }
        }
        
        internal static string Distance_to_water_when_full__100__ {
            get {
                return ResourceManager.GetString("Distance to water when full (100%)", resourceCulture);
            }
        }
        
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        internal static string Send_login_link {
            get {
                return ResourceManager.GetString("Send login link", resourceCulture);
            }
        }
    }
}
