//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Resources.Pages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccountSensor {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountSensor() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Site.Resources.Pages.AccountSensor", typeof(AccountSensor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string No_sensor_found_with_the_specified_Id_ {
            get {
                return ResourceManager.GetString("No sensor found with the specified Id.", resourceCulture);
            }
        }
        
        internal static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        internal static string Graph_6h {
            get {
                return ResourceManager.GetString("Graph 6h", resourceCulture);
            }
        }
        
        internal static string Graph_24h {
            get {
                return ResourceManager.GetString("Graph 24h", resourceCulture);
            }
        }
        
        internal static string Graph_7d {
            get {
                return ResourceManager.GetString("Graph 7d", resourceCulture);
            }
        }
        
        internal static string Graph_3m {
            get {
                return ResourceManager.GetString("Graph 3m", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        internal static string Trend {
            get {
                return ResourceManager.GetString("Trend", resourceCulture);
            }
        }
        
        internal static string QR_Code {
            get {
                return ResourceManager.GetString("QR Code", resourceCulture);
            }
        }
    }
}
